name: Liquibase Update

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  liquibase-update:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      
      - name: Download Liquibase
        run: |
          wget -q -O liquibase.tar.gz https://github.com/liquibase/liquibase/releases/download/v4.24.0/liquibase-4.24.0.tar.gz
          tar -xzf liquibase.tar.gz
          chmod +x liquibase
      
      - name: Download PostgreSQL Driver
        run: |
          wget -q -O postgresql.jar https://jdbc.postgresql.org/download/postgresql-42.7.0.jar
          mkdir -p lib
          mv postgresql.jar lib/
      
      - name: Validate Changelog
        run: |
          ./liquibase --changeLogFile=liquibase/changelog-master.xml \
                      --classpath=lib/postgresql.jar \
                      validate
      
      - name: Run Liquibase Update
        run: |
          ./liquibase --changeLogFile=liquibase/changelog-master.xml \
                      --classpath=lib/postgresql.jar \
                      update
        env:
          LIQUIBASE_COMMAND_URL: ${{ secrets.DATABASE_URL }}
          LIQUIBASE_COMMAND_USERNAME: ${{ secrets.DATABASE_USERNAME }}
          LIQUIBASE_COMMAND_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
